name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'  # Ensure this matches the Node.js version required by Strapi

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: npm run build

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USER }}
          KEY: ${{ secrets.SERVER_KEY }}
        run: |
          ssh -i $KEY $USERNAME@$HOST "cd strapi && git pull && npm install && npm run build && pm2 restart strapi"
